name: "GetExtraParameters"
description: "Provides extra parameters for downstream Jenkins jobs"
author: "Miklos Gergely"
inputs:
  access_token:
    description: "GitHub token"
    required: true
  config_file_name:
    description: "Name of the config file to be used, e.g.: job_config.json"
    required: true
  parameters:
    description: "Base parameters that can be overwritten, must be valid json"
    required: false
    default: '{}'
outputs:
  extra_parameters:
    description: "extra parameters"
runs:
  using: "docker"
  image: "../get_extra_parameters.Dockerfile"
